# ruff: noqa: ANN201, D103, D400, D415, E501, I001, N999, Q000, RUF001, RUF100, W291
"""initial_schema

Revision ID: 7c767a61d67e
Revises:
Create Date: 2026-05-21 19:44:17.085681

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision = '7c767a61d67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_storage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='存储名称'),
    sa.Column('endpoint', sa.String(length=512), nullable=False, comment='终端节点'),
    sa.Column('access_key', sa.String(length=512), nullable=False, comment='访问密钥'),
    sa.Column('secret_key', sa.String(length=512), nullable=False, comment='密钥'),
    sa.Column('bucket', sa.String(length=64), nullable=False, comment='存储桶'),
    sa.Column('prefix', sa.String(length=256), nullable=True, comment='前缀'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='区域'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='S3 存储.'
    )
    op.create_index(op.f('ix_s3_storage_id'), 's3_storage', ['id'], unique=True)
    op.create_table('sys_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='名称'),
    sa.Column('type', sa.String(length=32), nullable=True, comment='类型'),
    sa.Column('key', sa.String(length=64), nullable=False, comment='键名'),
    sa.Column('value', backend.common.model.UniversalText(), nullable=False, comment='键值'),
    sa.Column('is_frontend', sa.Boolean(), nullable=False, comment='是否前端'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    comment='参数配置表.'
    )
    op.create_index(op.f('ix_sys_config_id'), 'sys_config', ['id'], unique=True)
    op.create_table('sys_data_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=512), nullable=False, comment='名称'),
    sa.Column('model', sa.String(length=64), nullable=False, comment='模型名称'),
    sa.Column('column', sa.String(length=32), nullable=False, comment='模型字段名'),
    sa.Column('operator', sa.Integer(), nullable=False, comment='运算符 (0: and, 1: or)'),
    sa.Column('expression', sa.Integer(), nullable=False, comment='表达式 (0: ==, 1: !=, 2: >, 3: >=, 4: <, 5: <=, 6: in, 7: not_in)'),
    sa.Column('value', sa.String(length=256), nullable=False, comment='规则值'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='数据规则表.'
    )
    op.create_index(op.f('ix_sys_data_rule_id'), 'sys_data_rule', ['id'], unique=True)
    op.create_table('sys_data_scope',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态 (0停用 1正常)'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='数据范围表.'
    )
    op.create_index(op.f('ix_sys_data_scope_id'), 'sys_data_scope', ['id'], unique=True)
    op.create_table('sys_data_scope_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('data_scope_id', sa.BigInteger(), nullable=False, comment='数据范围 ID'),
    sa.Column('data_rule_id', sa.BigInteger(), nullable=False, comment='数据规则 ID'),
    sa.PrimaryKeyConstraint('id', 'data_scope_id', 'data_rule_id')
    )
    op.create_index(op.f('ix_sys_data_scope_rule_id'), 'sys_data_scope_rule', ['id'], unique=True)
    op.create_table('sys_dept',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('leader', sa.String(length=32), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('status', sa.Integer(), nullable=False, comment='部门状态(0停用 1正常)'),
    sa.Column('del_flag', sa.Boolean(), nullable=False, comment='删除标志(0删除 1存在)'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门ID'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表.'
    )
    op.create_index(op.f('ix_sys_dept_id'), 'sys_dept', ['id'], unique=True)
    op.create_index(op.f('ix_sys_dept_parent_id'), 'sys_dept', ['parent_id'], unique=False)
    op.create_table('sys_dict_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('type_code', sa.String(length=32), nullable=False, comment='对应的字典类型编码'),
    sa.Column('label', sa.String(length=32), nullable=False, comment='字典标签'),
    sa.Column('value', sa.String(length=32), nullable=False, comment='字典值'),
    sa.Column('color', sa.String(length=32), nullable=True, comment='标签颜色'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0停用 1正常)'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('type_id', sa.BigInteger(), nullable=False, comment='字典类型关联ID'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典数据表.'
    )
    op.create_index(op.f('ix_sys_dict_data_id'), 'sys_dict_data', ['id'], unique=True)
    op.create_table('sys_dict_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='字典类型名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='字典类型编码'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='字典类型表.'
    )
    op.create_index(op.f('ix_sys_dict_type_id'), 'sys_dict_type', ['id'], unique=True)
    op.create_table('sys_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('user_uuid', sa.String(length=64), nullable=False, comment='用户UUID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('status', sa.Integer(), nullable=False, comment='登录状态(0失败 1成功)'),
    sa.Column('ip', sa.String(length=64), nullable=False, comment='登录IP地址'),
    sa.Column('country', sa.String(length=64), nullable=True, comment='国家'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='地区'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('user_agent', sa.String(length=256), nullable=False, comment='请求头'),
    sa.Column('os', sa.String(length=64), nullable=True, comment='操作系统'),
    sa.Column('browser', sa.String(length=64), nullable=True, comment='浏览器'),
    sa.Column('device', sa.String(length=64), nullable=True, comment='设备'),
    sa.Column('msg', backend.common.model.UniversalText(), nullable=False, comment='提示消息'),
    sa.Column('login_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='登录时间'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志表.'
    )
    op.create_index(op.f('ix_sys_login_log_id'), 'sys_login_log', ['id'], unique=True)
    op.create_table('sys_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='菜单标题'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单名称'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路由地址'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('icon', sa.String(length=128), nullable=True, comment='菜单图标'),
    sa.Column('type', sa.Integer(), nullable=False, comment='菜单类型(0目录 1菜单 2按钮 3内嵌 4外链)'),
    sa.Column('component', sa.String(length=256), nullable=True, comment='组件路径'),
    sa.Column('perms', sa.String(length=128), nullable=True, comment='权限标识'),
    sa.Column('status', sa.Integer(), nullable=False, comment='菜单状态(0停用 1正常)'),
    sa.Column('display', sa.Integer(), nullable=False, comment='是否显示(0否 1是)'),
    sa.Column('cache', sa.Integer(), nullable=False, comment='是否缓存(0否 1是)'),
    sa.Column('link', backend.common.model.UniversalText(), nullable=True, comment='外链地址'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表.'
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=True)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_table('sys_notice',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='标题'),
    sa.Column('type', sa.Integer(), nullable=False, comment='类型(0: 通知、1: 公告)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0: 隐藏、1: 显示)'),
    sa.Column('content', backend.common.model.UniversalText(), nullable=False, comment='内容'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统通知公告表.'
    )
    op.create_index(op.f('ix_sys_notice_id'), 'sys_notice', ['id'], unique=True)
    op.create_table('sys_opera_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('trace_id', sa.String(length=32), nullable=False, comment='请求跟踪 ID'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名'),
    sa.Column('method', sa.String(length=32), nullable=False, comment='请求类型'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='操作模块'),
    sa.Column('path', sa.String(length=512), nullable=False, comment='请求路径'),
    sa.Column('ip', sa.String(length=64), nullable=False, comment='IP地址'),
    sa.Column('country', sa.String(length=64), nullable=True, comment='国家'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='地区'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('user_agent', sa.String(length=512), nullable=False, comment='请求头'),
    sa.Column('os', sa.String(length=64), nullable=True, comment='操作系统'),
    sa.Column('browser', sa.String(length=64), nullable=True, comment='浏览器'),
    sa.Column('device', sa.String(length=64), nullable=True, comment='设备'),
    sa.Column('args', sa.JSON(), nullable=True, comment='请求参数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='操作状态(0异常 1正常)'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='操作状态码'),
    sa.Column('msg', backend.common.model.UniversalText(), nullable=True, comment='提示消息'),
    sa.Column('cost_time', sa.Float(), nullable=False, comment='请求耗时(ms)'),
    sa.Column('opera_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='操作时间'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作日志表.'
    )
    op.create_index(op.f('ix_sys_opera_log_id'), 'sys_opera_log', ['id'], unique=True)
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='角色名称'),
    sa.Column('status', sa.Integer(), nullable=False, comment='角色状态(0停用 1正常)'),
    sa.Column('is_filter_scopes', sa.Boolean(), nullable=False, comment='过滤数据权限(0否 1是)'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='角色表.'
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=True)
    op.create_table('sys_role_data_scope',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('data_scope_id', sa.BigInteger(), nullable=False, comment='数据范围 ID'),
    sa.PrimaryKeyConstraint('id', 'role_id', 'data_scope_id')
    )
    op.create_index(op.f('ix_sys_role_data_scope_id'), 'sys_role_data_scope', ['id'], unique=True)
    op.create_table('sys_role_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.PrimaryKeyConstraint('id', 'role_id', 'menu_id')
    )
    op.create_index(op.f('ix_sys_role_menu_id'), 'sys_role_menu', ['id'], unique=True)
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('password', sa.String(length=256), nullable=True, comment='密码'),
    sa.Column('salt', sa.LargeBinary(length=255), nullable=True, comment='加密盐'),
    sa.Column('email', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=256), nullable=True, comment='头像'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户账号状态(0停用 1正常)'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='超级权限(0否 1是)'),
    sa.Column('is_staff', sa.Boolean(), nullable=False, comment='后台管理登陆(0否 1是)'),
    sa.Column('is_multi_login', sa.Boolean(), nullable=False, comment='是否重复登陆(0否 1是)'),
    sa.Column('join_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='注册时间'),
    sa.Column('last_login_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='上次登录时间'),
    sa.Column('last_password_changed_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='上次密码变更时间'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门关联ID'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    comment='用户表.'
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('sys_user_password_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('password', sa.String(length=256), nullable=False, comment='历史密码'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户密码历史记录表.'
    )
    op.create_index(op.f('ix_sys_user_password_history_id'), 'sys_user_password_history', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_password_history_user_id'), 'sys_user_password_history', ['user_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'role_id')
    )
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user_role', ['id'], unique=True)
    op.create_table('sys_user_social',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('sid', sa.String(length=256), nullable=False, comment='第三方用户 ID'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='第三方用户来源'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户关联ID'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户社交表（OAuth2）.'
    )
    op.create_index(op.f('ix_sys_user_social_id'), 'sys_user_social', ['id'], unique=True)
    op.create_table('task_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=155), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=155), nullable=True),
    sa.Column('args', sa.LargeBinary(), nullable=True),
    sa.Column('kwargs', sa.LargeBinary(), nullable=True),
    sa.Column('worker', sa.String(length=155), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id'),
    comment='任务结果表'
    )
    op.create_table('task_scheduler',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('task', sa.String(length=256), nullable=False, comment='要运行的 Celery 任务'),
    sa.Column('args', sa.JSON(), nullable=True, comment='任务可接收的位置参数'),
    sa.Column('kwargs', sa.JSON(), nullable=True, comment='任务可接收的关键字参数'),
    sa.Column('queue', sa.String(length=256), nullable=True, comment='CELERY_TASK_QUEUES 中定义的队列'),
    sa.Column('exchange', sa.String(length=256), nullable=True, comment='低级别 AMQP 路由的交换机'),
    sa.Column('routing_key', sa.String(length=256), nullable=True, comment='低级别 AMQP 路由的路由密钥'),
    sa.Column('start_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='任务开始触发的时间'),
    sa.Column('expire_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='任务不再触发的截止时间'),
    sa.Column('expire_seconds', sa.Integer(), nullable=True, comment='任务不再触发的秒数时间差'),
    sa.Column('type', sa.Integer(), nullable=False, comment='调度类型(0间隔 1定时)'),
    sa.Column('interval_every', sa.Integer(), nullable=True, comment='任务再次运行前的间隔周期数'),
    sa.Column('interval_period', sa.String(length=256), nullable=True, comment='任务运行之间的周期类型'),
    sa.Column('crontab', sa.String(length=64), nullable=True, comment='任务运行的 Crontab 计划'),
    sa.Column('one_off', sa.Boolean(), nullable=False, comment='是否仅运行一次'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用任务'),
    sa.Column('total_run_count', sa.Integer(), nullable=False, comment='任务触发的总次数'),
    sa.Column('last_run_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='任务最后触发的时间'),
    sa.Column('remark', backend.common.model.UniversalText(), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='任务调度表.'
    )
    op.create_index(op.f('ix_task_scheduler_id'), 'task_scheduler', ['id'], unique=True)
    op.create_table('task_set_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', sa.String(length=155), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskset_id'),
    comment='任务集结果表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_set_result')
    op.drop_index(op.f('ix_task_scheduler_id'), table_name='task_scheduler')
    op.drop_table('task_scheduler')
    op.drop_table('task_result')
    op.drop_index(op.f('ix_sys_user_social_id'), table_name='sys_user_social')
    op.drop_table('sys_user_social')
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_user_password_history_user_id'), table_name='sys_user_password_history')
    op.drop_index(op.f('ix_sys_user_password_history_id'), table_name='sys_user_password_history')
    op.drop_table('sys_user_password_history')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_menu_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_role_data_scope_id'), table_name='sys_role_data_scope')
    op.drop_table('sys_role_data_scope')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_opera_log_id'), table_name='sys_opera_log')
    op.drop_table('sys_opera_log')
    op.drop_index(op.f('ix_sys_notice_id'), table_name='sys_notice')
    op.drop_table('sys_notice')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_login_log_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_dict_type_id'), table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_data_id'), table_name='sys_dict_data')
    op.drop_table('sys_dict_data')
    op.drop_index(op.f('ix_sys_dept_parent_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_id'), table_name='sys_dept')
    op.drop_table('sys_dept')
    op.drop_index(op.f('ix_sys_data_scope_rule_id'), table_name='sys_data_scope_rule')
    op.drop_table('sys_data_scope_rule')
    op.drop_index(op.f('ix_sys_data_scope_id'), table_name='sys_data_scope')
    op.drop_table('sys_data_scope')
    op.drop_index(op.f('ix_sys_data_rule_id'), table_name='sys_data_rule')
    op.drop_table('sys_data_rule')
    op.drop_index(op.f('ix_sys_config_id'), table_name='sys_config')
    op.drop_table('sys_config')
    op.drop_index(op.f('ix_s3_storage_id'), table_name='s3_storage')
    op.drop_table('s3_storage')
    # ### end Alembic commands ###
